### ISSUE TITLE
A função saveCamper tem um erro

### ISSUE THREAD

**Issue by AndreiaPatrocinio** [DiogoJorge97/GoCamping#39]
public Camper saveCamper(String username, String fullname, String email, int NIF, int campsiteCard) {
        Camper camper1 = new Camper();
        System.out.println("new camper");
        try {
            utx.begin();
            camper1.setUsername(username);
            camper1.setFullName(fullname);
            camper1.setEmail(email);
            camper1.setNIF(NIF);
            camper1.setCampsiteCard(campsiteCard);
            getEntityManager().persist(camper1);
            utx.commit();
        } catch (IllegalStateException | SecurityException | HeuristicMixedException | HeuristicRollbackException | NotSupportedException | RollbackException | SystemException e) {
            System.out.println("save didn't work on camper");
        }
        return camper;
    }  
tem de se substituir, a culpa é do PEDRO

**Comment by cmalbuquerque** [comment]
Eu já vejo isso, já que estou a mexer no projeto.
e esse return está mal. Vou substituir por isto:

`public Camper saveCamper(String username, String fullname, String email, int NIF, int campsiteCard) {
Camper camper1 = new Camper();
System.out.println("new camper");
try {
utx.begin();
camper1.setUsername(username);
camper1.setFullName(fullname);
camper1.setEmail(email);
camper1.setNIF(NIF);
camper1.setCampsiteCard(campsiteCard);
getEntityManager().persist(camper1);
utx.commit();
} catch (IllegalStateException | SecurityException | HeuristicMixedException | HeuristicRollbackException | NotSupportedException | RollbackException | SystemException e) {
System.out.println("save didn't work on camper");
}
return camper1;
}`

**Comment by cmalbuquerque** [comment]
Já está atualizada e colocada numa branch que criei
