### ISSUE TITLE
Teste de Selenium com problemas

### ISSUE THREAD

**Issue by cmalbuquerque** [DiogoJorge97/GoCamping#40]
É o seguinte, o teste de selenium à parte do Manager está a funcionar e a passar, mas para isso é sempre necessário que o servidor esteja sempre ligado. 
**Problema 1:** quando se faz Clean and Build do project, como o servidor está a correr, dá estoiro porque não pode criar o projeto na porta em questão.
**Problema 2:** depois na VM dá bosta porque o endereço retirado do teste é localhost enquanto que não deveria de ser

**Comment by PePirex** [comment]
Com o ultimo pull request do branch 'selenium' da Carolina ela resolveu estes problemas pelo que se pode fechar este issue.
